/**
 * Importing npm packages
 */
import { InferInsertModel } from 'drizzle-orm';

/**
 * Importing user defined packages
 */
import * as schema from '@server/database/schemas';

/**
 * Defining types
 */
type TemplateVariantInsertModel = InferInsertModel<typeof schema.templateVariants>;

/**
 * Declaring the constants
 */
export const templateVariants: TemplateVariantInsertModel[] = [
  {
    id: 1n,
    templateGroupId: 1n,
    channel: 'EMAIL',
    locale: 'en-US',
    subject: 'Welcome to Shadow',
    body: 'Hi {{name}}, thanks for signing up!',
    isActive: true,
  },
  {
    id: 2n,
    templateGroupId: 1n,
    channel: 'SMS',
    locale: 'en-US',
    body: 'Welcome {{name}}, your account is ready.',
    isActive: true,
  },
  {
    id: 3n,
    templateGroupId: 2n,
    channel: 'EMAIL',
    locale: 'en-US',
    subject: 'Reset your password',
    body: 'Click here to reset: {{resetLink}}',
    isActive: true,
  },
  {
    id: 4n,
    templateGroupId: 3n,
    channel: 'EMAIL',
    locale: 'en-US',
    subject: 'Your weekly newsletter',
    body: 'Latest updates and news.',
    isActive: true,
  },
  {
    id: 5n,
    templateGroupId: 4n,
    channel: 'PUSH',
    locale: 'en-US',
    subject: 'Account alert',
    body: 'Unusual activity detected on your account.',
    isActive: true,
  },
  {
    id: 6n,
    templateGroupId: 1n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Welcome to Shadow',
    body: 'Hi {{name}}, thanks for signing up!',
    isActive: true,
  },
  {
    id: 7n,
    templateGroupId: 1n,
    channel: 'SMS',
    locale: 'en-ZZ',
    body: 'Welcome {{name}}, your account is ready.',
    isActive: true,
  },
  {
    id: 8n,
    templateGroupId: 2n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Reset your password',
    body: 'Click here to reset: {{resetLink}}',
    isActive: true,
  },
  {
    id: 9n,
    templateGroupId: 3n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Your weekly newsletter',
    body: 'Latest updates and news.',
    isActive: true,
  },
  {
    id: 10n,
    templateGroupId: 4n,
    channel: 'PUSH',
    locale: 'en-ZZ',
    subject: 'Account alert',
    body: 'Unusual activity detected on your account.',
    isActive: true,
  },

  /** Identity-server notification catalog: identity sends no locale, so pulse resolves the en-ZZ default variant */
  {
    id: 11n,
    templateGroupId: 6n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Your registration code',
    body: 'Your Shadow registration code is {{code}}. It expires in 10 minutes. If you did not request this, you can ignore this email.',
    isActive: true,
  },
  {
    id: 12n,
    templateGroupId: 6n,
    channel: 'SMS',
    locale: 'en-ZZ',
    body: '{{code}} is your Shadow registration code. It expires in 10 minutes.',
    isActive: true,
  },
  {
    id: 13n,
    templateGroupId: 7n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Your sign-in code',
    body: 'Your Shadow sign-in code is {{code}}. It expires in 10 minutes. If you did not request this, please secure your account.',
    isActive: true,
  },
  {
    id: 14n,
    templateGroupId: 7n,
    channel: 'SMS',
    locale: 'en-ZZ',
    body: '{{code}} is your Shadow sign-in code. It expires in 10 minutes.',
    isActive: true,
  },
  {
    id: 15n,
    templateGroupId: 8n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Your account recovery code',
    body: 'Your Shadow account recovery code is {{code}}. It expires in 10 minutes. If you did not request this, you can ignore this email.',
    isActive: true,
  },
  {
    id: 16n,
    templateGroupId: 9n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Your password was changed',
    body: 'The password for your Shadow account was changed from IP address {{ipAddress}}. If this was not you, reset your password immediately.',
    isActive: true,
  },
  {
    id: 17n,
    templateGroupId: 10n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Two-factor authentication enabled',
    body: 'Two-factor authentication using {{method}} was enabled on your Shadow account. If this was not you, review your account security.',
    isActive: true,
  },
  {
    id: 18n,
    templateGroupId: 11n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Two-factor authentication disabled',
    body: 'Two-factor authentication using {{method}} was disabled on your Shadow account. If this was not you, review your account security.',
    isActive: true,
  },
  {
    id: 19n,
    templateGroupId: 12n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'A recovery code was used',
    body: 'A recovery code was used to access your Shadow account. You have {{remaining}} recovery codes remaining. If this was not you, review your account security.',
    isActive: true,
  },
  {
    id: 20n,
    templateGroupId: 13n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'New sign-in to your account',
    body: 'A new sign-in to your Shadow account was detected at {{time}} from IP address {{ipAddress}} using {{userAgent}}. If this was not you, secure your account immediately.',
    isActive: true,
  },
  {
    id: 21n,
    templateGroupId: 14n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Verify your email address',
    body: 'Your Shadow email verification code is {{code}}. It expires in 10 minutes.',
    isActive: true,
  },
  {
    id: 22n,
    templateGroupId: 15n,
    channel: 'SMS',
    locale: 'en-ZZ',
    body: '{{code}} is your Shadow phone verification code. It expires in 10 minutes.',
    isActive: true,
  },
  {
    id: 23n,
    templateGroupId: 16n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Your contact details were updated',
    body: 'The {{type}} contact on your Shadow account was updated ({{action}}). If you did not make this change, review your account security.',
    isActive: true,
  },
  {
    id: 24n,
    templateGroupId: 17n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'You have been invited to join {{organisationName}}',
    body: 'You have been invited to join {{organisationName}} as {{role}}. Use the invitation code {{token}} to accept the invitation.',
    isActive: true,
  },
  {
    id: 25n,
    templateGroupId: 18n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'Your organisation role was changed',
    body: 'Your role in the organisation has been changed to {{role}}.',
    isActive: true,
  },
  {
    id: 26n,
    templateGroupId: 19n,
    channel: 'EMAIL',
    locale: 'en-ZZ',
    subject: 'You were removed from an organisation',
    body: 'Your membership in the organisation has been removed. If you believe this is a mistake, contact the organisation administrator.',
    isActive: true,
  },
];
